name: Export Docker Image to TAR

on:
  workflow_dispatch:

jobs:
  export-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image from GCR
        run: docker pull gcr.io/kaggle-gpu-images/python:latest

      - name: Save Docker image as TAR
        run: docker save -o kaggle-python.tar gcr.io/kaggle-gpu-images/python:latest

      - name: Upload TAR as artifact
        uses: actions/upload-artifact@v3.1.2  # Dùng version cụ thể
        with:
          name: kaggle-docker-image
          path: kaggle-python.tar
